### PR TITLE
Change "Recovery Passphrase/Key" to "Security Phrase/Key"

### PR DESCRIPTION
**Pull request by ChristianGynnild**
## Type of change

- [ ] Feature
- [ ] Bugfix
- [ ] Technical
- [x] Other :

## Content

Change outdated phrases "Recovery Key" and "Recovery Passphrase" to "Security Key" and "Security Phrase"

## Motivation and context

Fixes https://github.com/vector-im/element-android/issues/2726
Improves https://github.com/vector-im/element-meta/issues/1474

## Checklist

- [x] Changes has been tested on an Android device or Android emulator with API 21
- [x] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [x] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [x] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

### CODE REVIEW

**Comment by ChristianGynnild** [comment]
Signed-off-by: Christian Gynnild Christianwgynnild@proton.me

**Comment by ChristianGynnild** [comment]
Rebased the commits to the latest version of the develop branch

**Comment by richvdh** [comment]
@BillCarsonFr we should close this, right?

**Comment by richvdh** [comment]
Closing, as per https://github.com/element-hq/element-android/issues/2726#issuecomment-2223252645

**Comment by richvdh** [comment]
(@ChristianGynnild: thank you for the work, and apologies on behalf of the android team that this never got looked at.)

**Pull request closed without merging**
